//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CELLULAR.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CELLULAR_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDC_EDIT_STATUS                 1000
#define IDC_STATUS_TEXT                 1001
#define IDC_EDIT_PHONE                  1002
#define IDC_EDIT_NAME                   1003
#define IDC_EDIT_NAME2                  1004
#define IDC_EDIT_OCCUPATION             1005
#define IDC_EDIT_AREA                   1006
#define IDC_BUTTON_SKIPVOICECALL        1007
#define IDC_BUTTON_SAVE_DATA            1008
#define IDC_BUTTON_FIND_PHONE           1009
#define IDC_CHECK_HOLDCALL              1010
#define IDC_TEXT_TOTALCALL              1011
#define IDC_EDIT_SUBJECT                1012
#define IDC_EDIT_GENDER                 1013
#define IDC_EDIT_LANGUAGE               1014
#define IDC_TEXT_CALLSLEVEL0            1015
#define IDC_EDIT_DTMF                   1016
#define IDC_EDIT_LINKEDFILE             1017
#define IDC_EDIT_INFO1                  1018
#define IDC_EDIT_INFO2                  1019
#define IDC_EDIT_INFO3                  1020
#define IDC_EDIT_PHONETYPE              1021
#define IDC_EDIT_PHONEMODEL             1022
#define IDC_EDIT_ESN                    1023
#define IDC_EDIT_SCM                    1024
#define IDC_EDIT_LASTCALL               1025
#define IDC_EDIT_TOTALCALLS             1026
#define IDC_EDIT_MODEMCALL              1027
#define IDC_EDIT_FAXCALLS               1028
#define IDC_EDIT_ALERTLEVEL             1029
#define IDC_EDIT_RECORDCALL             1030
#define IDC_TEXT_CALLSLEVEL1            1031
#define IDC_EDIT_CHANNELAB              1032
#define IDC_EDIT_CALLSTART              1033
#define IDC_EDIT_CALLEND                1034
#define IDC_EDIT_CALLTIME               1035
#define IDC_EDIT_SIGNALSTR              1036
#define IDC_EDIT_DIALEDNUMBER           1037
#define IDC_TEXT_CALLSLEVEL2            1038
#define IDC_TEXT_CALLSLEVEL3            1039
#define IDC_TEXT_CALLSLEVEL4            1040
#define IDC_TEXT_CALLSLEVEL5            1041
#define IDC_TEXT_CALLSLEVEL6            1042
#define IDC_TEXT_CALLSLEVEL7            1043
#define IDC_TEXT_CALLSLEVEL8            1044
#define IDC_TEXT_CALLSLEVEL9            1045
#define IDC_TEXT_CALLSMODEM             1046
#define IDC_TEXT_CALLSFAX               1047
#define IDC_TEXT_CALLSRECORD            1048
#define IDC_EDIT_CALLS                  1049
#define IDC_CHECK_AQUIRE                1050
#define IDC_CHECK_MONITOR               1051
#define IDC_BUTTON_SWITCHVOICE          1052
#define IDC_TEXT_FREQUENCY              1053
#define IDC_TEXT_CHANNELTYPE            1054
#define IDC_TEXT_NPC                    1055
#define IDC_TEXT_NAC                    1056
#define IDC_TEXT_REGINC                 1057
#define IDC_TEXT_MODES_S                1058
#define IDC_TEXT_MODES_E                1059
#define IDC_TEXT_MODES_R                1060
#define IDC_TEXT_MODES_F                1061
#define IDC_TEXT_MODES_H                1062
#define IDC_TEXT_MODES_D                1063
#define IDC_TEXT_MODES_C                1064
#define IDC_TEXT_SID                    1065
#define IDC_TEXT_DCC                    1066
#define IDC_BUTTON_CONTROL_TYPE         1067
#define IDC_BUTTON_CONTROLSCAN          1068
#define IDC_PROGRESS_SIGNAL             1069

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
