// ATTRDEFS.H - Default Attribute Definitions

#ifndef ATTRDEFS_H
#define ATTRDEFS_H

#define attrINPUT  LIGHTGREY
#define attrLEGEND WHITE
#define attrBMNORM (BLUE << 4) | YELLOW
#define attrBMHIGH (CYAN << 4) | BLUE
#define attrBMHOTK (BLUE << 4) | WHITE
#define attrMNORM  (MAGENTA << 4) | WHITE
#define attrMHIGH  (CYAN << 4)
#define attrBNORM  (MAGENTA << 4) | WHITE
#define attrBHIGH  (CYAN << 4)
#define attrTITLE  (BLUE << 4) | WHITE
#define attrPRCOL  (BLUE << 4) | WHITE
#define attrSCREEN LIGHTGREY

#endif
